### PR TITLE
Fix `canonical_gauge(::PSOModel)`

### PR DESCRIPTION
**Pull request by ajkeller34**
`canonical_gauge` was not always behaving as advertised. It appears this is related to differing implementations of QR factorization for dense v. sparse matrices. I have not looked into why this happens so if it is obvious to someone I'd appreciate a comment being left here.

There was a test for this function, but apparently it was not strong enough, so I added a test that covers a case where the function was misbehaving. I don't expect my fix to impact performance much, since I think `canonical_gauge` already densified PSO models before this PR.

### CODE REVIEW

**Comment by ecpeterson** [comment]
I'd believe that dense QR and sparse QR might give literally different factorizations (especially since `P` is rectangular—right?), but I can't imagine why the rest of the code would care.

It'd be worth sanity-checking that sparse QR is at least giving a _correct_ factorization, so that the problem is for sure somewhere in our code and not in Julia linear algebra.

**Comment by ecpeterson** [comment]
I'll approve this change, since it's important to have correct code in master—but conditional on you filing an issue for someone to investigate further and figure out how to get sparsity back.

**Comment by mgscheer** [comment]
Just a note: this function generically produces dense models anyway (see the comment on line 82 of admittance_model.jl) so I don't think one should worry about getting sparsity back.

**Comment by ecpeterson** [comment]
nice

**Comment by onurbakir** [comment]
Is this a uniqueness issue? Can QR with pivoting help?

**Comment by mgscheer** [comment]
Well according to Wikipedia QR decomposition is unique (under basic assumptions) so I don't think there's anything one can do. Circuits generically have sparse high dimensional PSO models but dense low dimensional transfer functions.

**Comment by ajkeller34** [comment]
For those interested I just took another look, there are different types returned depending on whether you attempt QR factorization on a sparse or dense matrix. The `SuiteSparse.SPQR.QRSparse` type includes some row and column permutations we were ignoring. Something to keep in mind for the future but probably expected behavior.

**Comment by onurbakir** [comment]
That’s what I thought. I was using rank revealing QR in Matlab quite a while ago. That was returning a sorted QR with a permutation matrix so that you can compress a dense matrix with not too much effort.

**Pull request merged**
