### PR TITLE
Remove `Cascade` from AdmittanceModels

### PR DESCRIPTION
**Pull request by ajkeller34**
…and adjust all examples and tests accordingly.

`Cascade` can be convenient, but:

1. Its purpose not scoped well. It does not cascade anything, rather it holds onto components that could be cascaded later. But in practice, they are always cascaded with common ports united, followed by arbitrary operations on the other ports.

2. Because it is not scoped well, it is confusing to new users.

3. It is not type-stable, so any usage in a function is likely to result in an unnecessary performance hit. It could potentially be made type-stable by introducing a tuple of functions into a type parameter, e.g. `Cascade{(short_ports,)}`, but there would be a new type for each permutation of port operations you want to do. That sounds unnecessary for a type that is ultimately just for sake of convenience.

I suggest we remove this for now to discourage use, until a better solution is implemented.

### CODE REVIEW

**Comment by mgscheer** [comment]
Hey Andrew,
My intention with Cascade was to represent a combination of CircuitComponent objects connected in a specified way. I understand your points, but I also like the idea of being able to create an abstract representation of the system separately from it's concrete PSOModel or Blackbox implementation. This is implemented for transmission lines and capacitors etc with CircuitComponents, and for their combinations using Cascade. Do you not see this as a useful abstraction? Or can you think of a better way to achieve it than Cascade?

**Comment by ajkeller34** [comment]
Hi Michael,

Thanks for the chat earlier. Below are my detailed comments: 

> My intention with Cascade was to represent a combination of CircuitComponent objects connected in a specified way.

If I understand correctly you wanted an abstraction in which you can have a set of `CircuitComponent` objects, representing physically realizable components like transmission lines, capacitors, etc., and some notion of how they are connected. In general I appreciate the motivation. In practice though, you can only ever cascade *either* PSO models *or* Blackbox models. With a cascade of components, only one kind of model is ultimately realized, so I'm not convinced of a net win given the likely performance issues. 

I think something similar to `Cascade` might be a useful abstraction if we had more varieties of AdmittanceModels, and in particular more complicated model composition requirements (see the `compatibility` functions). You could maybe imagine some type keeping track of how to compose different kinds of admittance models representing different parts of a circuit. I'm just speculating though.

> I understand your points, but I also like the idea of being able to create an abstract representation of the system separately from its concrete PSOModel or Blackbox implementation. This is implemented for transmission lines and capacitors etc with CircuitComponents, and for their combinations using Cascade.

Having abstractions for e.g. `TransmissionLine` makes sense to me because a physical transmission line could be represented in a few ways: as a lumped element ladder, blackbox response, or by an analytic treatment, etc. In that sense it seems very natural to build PSO or Blackbox models out of a simplified, few-parameter `TransmissionLine` object. I'm less convinced about `Cascade` though, which represents neither a physical thing nor a type of model, really (you can't easily make predictions with it alone). I guess you could argue it does represent a physical thing, but not in a particularly structured way.

> Or can you think of a better way to achieve it than Cascade?

If you like declaring in advance what should be done to port terminations, I would guess that a more performant way to achieve that would be to define a `Port` type with some extra info encoded in it. This could be used instead of `String`s. The remaining functionality of `Cascade` amounts to maybe saving a bit of typing: `PSOModel(Cascade([components], [port_ops]))` becomes `cascade_and_unite(PSOModel.([components...]))`, and `Blackbox(omega,  Cascade([components], [port_ops]))` becomes `cascade_and_unite(Blackbox.(Ref(omega), [components]))`. (`Ref` is a Julia idiom for treating something as a scalar for the purposes of broadcasting.)

I hope that clarifies my reasoning about it!

**Comment by mgscheer** [comment]
Hi Andrew,

Thanks for the thorough reply! After some thought, I agree that Cascade is not really necessary and given that things are generally more readable without it I'm in favor of making this change. I do like being able to specify what happens to the ports ahead of time though, as this would avoid some repeated code in the code for the paper. So if you have ideas for a better way to do that, that would be cool, though it's not that important. I hope you're doing well!

**Comment by ajkeller34** [comment]
@mgscheer thank you for looking over this again, it is much appreciated! I will think about how port termination could be improved.

**Pull request merged**
